#pragma once

#include <d3d9.h>

typedef enum 
{
	TEXTURE_INDEX_NUMBER,
	TEXTURE_INDEX_NUMBER_BLUE,
	TEXTURE_INDEX_NUMBER_RED,
	TEXTURE_INDEX_SELECTCHARA,
	TEXTURE_INDEX_SELECTCORSOR1P,
	TEXTURE_INDEX_SELECTCORSOR2P,
	TEXTURE_INDEX_SIGHT,
	TEXTURE_INDEX_VENUE,
	TEXTURE_INDEX_COUNTDOWN,
	TEXTURE_INDEX_START,
	TEXTURE_INDEX_TIMEUP,
	TEXTURE_INDEX_1P,
	TEXTURE_INDEX_2P,
	TEXTURE_INDEX_4P,
	TEXTURE_INDEX_WIN,
	TEXTURE_INDEX_DRAW,
	TEXTURE_INDEX_PLAY2,
	TEXTURE_INDEX_ARROWPOWER_BAR,
	TEXTURE_INDEX_ARROWPOWERBOX_BAR,
	TEXTURE_INDEX_RESULT_BAR,
	TEXTURE_INDEX_TITLE_2,
	TEXTURE_INDEX_FLAG_JPN,
	TEXTURE_INDEX_FLAG_USA,
	TEXTURE_INDEX_FLAG_KOR,
	TEXTURE_INDEX_FLAG_FRA,
	TEXTURE_INDEX_CHOSE,
	TEXTURE_INDEX_KUSSA,
	TEXTURE_INDEX_EXPLAIN,
	TEXTURE_INDEX_LOGO,
    TEXTURE_INDEX_MAX

}TextureIndex;

int Texture_Load(void); //èâä˙âª
void Texture_Release(void); //èIóπèàóù
LPDIRECT3DTEXTURE9 Texture_GetTexture(TextureIndex index);
int Texture_GetWidth(TextureIndex index);
int Texture_GetHeight(TextureIndex index);
void SetTexture(TextureIndex index);
void ReleaseTexture(TextureIndex index);
